- name: ransomware-detector
  rule: 
    type: cel
    params:
      expression: "event.severity == 'high' && event.tags.exists(tag, tag == 'ransomware')"
  action:
    type: parallel
    params:
      name: "Ransomware playbook"
      children:
        - type: print
          params:
            name: Log request
            message: "1/3 Ransomware detected! Initiating response..."
        - type: print
          params:
            name: Isolate endpoint
            message: "2/3 Isolating endpoint"
        - type: print
          params:
            name: Network scan
            message: "3/3 scanning network for threats"

- name: suspicious-login-detector
  rule:
    type: cel
    params:
      expression: "event.severity == 'medium' && event.tags.exists(tag, tag == 'suspicious-login')"
  action:
    type: print
    params:
      name: Log message
      message: "Suspicious login detected!"

- name: Auto-escalate-urgent
  rule:
    type: cel
    params:
      expression: "event.tags.exists(tag, tag == 'urgent')"
  action:
    type: print
    params:
      name: Escalate to case
      message: "Automatically escalating urgent event into case"
